emit:
- '@azure-tools/typespec-autorest'
linter:
  extends:
  - '@azure-tools/typespec-azure-rulesets/resource-manager'
options:
  '@azure-tools/typespec-autorest':
    arm-types-dir: '{project-root}/../../../../common-types/resource-management'
    azure-resource-provider-folder: resource-manager
    emit-lro-options: all
    emitter-output-dir: '{project-root}'
    examples-dir: '{project-root}/examples'
    omit-unreachable-types: true
    output-file: '{version-status}/{version}/openapi.json'
  '@azure-tools/typespec-go':
    emitter-output-dir: '{output-dir}/{service-dir}/armstoragecache'
    fix-const-stuttering: true
    flavor: azure
    generate-fakes: true
    generate-samples: true
    head-as-boolean: true
    inject-spans: true
    module: github.com/Azure/azure-sdk-for-go/{service-dir}/armstoragecache
    service-dir: sdk/resourcemanager/storagecache
  '@azure-tools/typespec-java':
    emitter-output-dir: '{output-dir}/{service-dir}/azure-resourcemanager-storagecache'
    flavor: azure
    namespace: com.azure.resourcemanager.storagecache
    service-name: StorageCache
  '@azure-tools/typespec-python':
    api-version: '2026-01-01'
    emitter-output-dir: '{output-dir}/{service-dir}/azure-mgmt-storagecache'
    flavor: azure
    generate-sample: true
    generate-test: true
    namespace: azure.mgmt.storagecache
  '@azure-tools/typespec-ts':
    compatibility-lro: true
    emitter-output-dir: '{output-dir}/{service-dir}/arm-storagecache'
    experimental-extensible-enums: true
    flavor: azure
    package-details:
      name: '@azure/arm-storagecache'
    service-dir: sdk/storagecache
parameters:
  service-dir:
    default: sdk/storagecache
